# Generated by Django 3.2 on 2022-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('birth_date', models.DateTimeField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
